### ISSUE TITLE
main.go failed to build: fcgiwork\fcgi.go:122: undefined: fcgiclient in fcgiclient.DialTimeout

### ISSUE THREAD

**Issue by tinogoehlert** [devTransition/job-go-fcgi-proxy#3]
there is a missing Dependency in fcgiwork\fcgi.go.

i think with adding "github.com/devTransition/job-go-fcgi-proxy/proxy" back to the imports in that file, the problem should be solved.

**Comment by valichek** [comment]
@tinogoehlert  ah, yes, broken imports ;) but will fix

**Comment by valichek** [comment]
thx for checking

**Comment by valichek** [comment]
fixed with https://github.com/devTransition/job-go-fcgi-proxy/commit/2db94da482db54f79b08aba34ac2d550e61d2ce3

**Comment by tinogoehlert** [comment]
no problem, thank you very much for fixing it :)
